CactusProject/Controllers/GraphController.cs
using CactusProject.Data;
using CactusProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CactusProject.Controllers
{
    public class GraphController : Controller
    {
        private readonly CactusContext cactusContext;

        public GraphController(CactusContext cactusContext)
        {
            this.cactusContext = cactusContext;
        }
        public async Task<IActionResult> Graph0(string status, DateTime? date = null)
        {
            List<OrderHeader> data;
            if (date != null)
            {
                data = await cactusContext.OrderHeaders
                    .Where(e => e.PaymentDate.Day.Equals(Convert.ToDateTime(date).Day) && e.PaymentDate.Month.Equals(Convert.ToDateTime(date).Month))
                    .ToListAsync();
            }
            else
            {
                data = await cactusContext.OrderHeaders.ToListAsync();
            }

            var sum = data.Where(c => c.OrderStatus == status).Sum(c => c.OrderTotal);

            List<DataPoint> dataPoints = new List<DataPoint>();

            foreach (var item in data)
            {
                if(status == item.OrderStatus)
                {
                    dataPoints.Add(new DataPoint(item.PaymentDate.ToString("dd/MM/yyyy"), (item.OrderTotal / sum) * 100, item.OrderTotal));
                }
            }

            if (sum > 0)
            {
                ViewBag.sumtotal = sum;
            }
            else
            {
                ViewBag.sumtotal = 0;
            }

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);

            return View();
        }

        public async Task<IActionResult> GraphOrder(string status = "Approved", DateTime? date = null)
        {
            await Graph0(status, date);
            return View();
        }

        public async Task<IActionResult> GraphOrder1(string status = "Approved", DateTime? date = null)
        {
            await Graph0(status, date);
            return View();
        }
        public async Task<IActionResult> GraphOrder2(string status = "Approved", DateTime? date = null)
        {
            await Graph0(status, date);
            return View();
        }
        public async Task<IActionResult> GraphOrder3(string status = "Approved", DateTime? date = null)
        {
            await Graph0(status, date);
            return View();
        }
        public async Task<IActionResult> GraphOrder4(string status = "Approved", DateTime? date = null)
        {
            await Graph0(status, date);
            return View();
        }
    }
}

CactusProject/Views/Graph/GraphOrder.cshtml
@using CactusProject.Utility
@{
    var dateY = DateTime.Now.ToString("yyyy");
}

<div class="text-center">

    <span class="dropdown-header">More Graph</span>

    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder"  asp-route-status="@SD.StatusApproved">Graph Pie</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder1" asp-route-status="@SD.StatusApproved">Graph Column</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder2" asp-route-status="@SD.StatusApproved">Graph Bar</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder3" asp-route-status="@SD.StatusApproved">Graph Pyramid</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder4" asp-route-status="@SD.StatusApproved">Graph SplineArea</a>

</div>



<div class="container text-dark mt-4">

    <form asp-action="GraphOrder">
      <label for="date">ดูยอดขาย:</label>
      <input type="date" name="date">
      <input type="submit">
    </form>

    <div class="bg-white"><h4>ยอดขายรวมทั้งหมด @dateY : @ViewBag.sumtotal</h4></div>
    <div id="chartContainer" style="height: 675px; width: 100%;"></div>
</div>

@section Scripts{
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                exportEnabled: true,
                animationEnabled: true,
                theme: "light2",// "light1", "light2", "dark1", "dark2"
                title: {
                    text: "ยอดขาย @dateY",
                    fontSize: 35
                },
                subtitles: [{
                    text: "2565 ถึง @dateY"
                }],
                legend: {
                    cursor: "pointer",
                    itemclick: explodePie,
                },
                data: [{
                    type: "pie",
                    toolTipContent: "{label} Pm - {z} Bath - {y}%",
                    startAngle: -45,
                    indexLabel: "{y}%",
                    indexLabelFontColor: "#000000",
                    indexLabelPlacement: "inside",
                    indexLabelFontSize: 20,
                    yValueFormatString: "#.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                    }]
            });
            chart.render();

            function explodePie(e) {
                if (typeof (e.dataSeries.dataPoints[e.dataPointIndex].exploded) === "undefined" || !e.dataSeries.dataPoints[e.dataPointIndex].exploded) {
                    e.dataSeries.dataPoints[e.dataPointIndex].exploded = true;
                } else {
                    e.dataSeries.dataPoints[e.dataPointIndex].exploded = false;
                }
                e.chart.render();
            }
        }
    </script>
 }

CactusProject/Views/Graph/GraphOrder1.cshtml
@using CactusProject.Utility
@{
    var dateY = DateTime.Now.ToString("yyyy");
}

<div class="text-center">

    <span class="dropdown-header">More Graph</span>

    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder" asp-route-status="@SD.StatusApproved">Graph Pie</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder1" asp-route-status="@SD.StatusApproved">Graph Column</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder2" asp-route-status="@SD.StatusApproved">Graph Bar</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder3" asp-route-status="@SD.StatusApproved">Graph Pyramid</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder4" asp-route-status="@SD.StatusApproved">Graph SplineArea</a>

</div>

<div class="container text-dark mt-4">
    <form asp-action="GraphOrder1">
      <label for="date">Date:</label>
      <input type="date" name="date">
      <input type="submit">
    </form>
    <div class="bg-white"><h4>ยอดขายรวมทั้งหมด @dateY : @ViewBag.sumtotal</h4></div>

    <div id="chartContainer" style="height: 675px; width: 100%;"></div>
</div>

@section Scripts{
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                theme: "light2", // "light1", "dark1", "dark2"
                exportEnabled: true,
                title: {
                    text: "ยอดขาย @dateY"
                },
                subtitles: [{
                    text: "2565 ถึง @dateY"
                }],
                data: [{
                   
                    type: "column",
                    toolTipContent: "{label} Pm - {z} Bath - {y}%",
                    startAngle: -45,
                    indexLabel: "{y}%",
                    indexLabelFontColor: "#000000",
                    indexLabelPlacement: "inside",
                    indexLabelFontSize: 20,
                    yValueFormatString: "#.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                }]
            });
            chart.render();

        }
    </script>
 }

CactusProject/Views/Graph/GraphOrder2.cshtml
@using CactusProject.Utility
@{
    var dateY = DateTime.Now.ToString("yyyy");
}

<div class="text-center">

    <span class="dropdown-header">More Graph</span>

    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder" asp-route-status="@SD.StatusApproved">Graph Pie</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder1" asp-route-status="@SD.StatusApproved">Graph Column</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder2" asp-route-status="@SD.StatusApproved">Graph Bar</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder3" asp-route-status="@SD.StatusApproved">Graph Pyramid</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder4" asp-route-status="@SD.StatusApproved">Graph SplineArea</a>

</div>

<div class="container text-dark mt-4">
    <form asp-action="GraphOrder2">
      <label for="date">Date:</label>
      <input type="date" name="date">
      <input type="submit">
    </form>
    <div class="bg-white"><h4>ยอดขายรวมทั้งหมด @dateY : @ViewBag.sumtotal</h4></div>

    <div id="chartContainer" style="height: 675px; width: 100%;"></div>
</div>

@section Scripts{
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                title: {
                    text: "ยอดขาย @dateY"
                },
                subtitles: [{
                    text: "2565 ถึง @dateY"
                }],
                data: [{
                    type: "bar",
                    toolTipContent: "{label} Pm - {z} Bath - {y}%",
                    startAngle: -45,
                    indexLabel: "{y}%",
                    indexLabelFontColor: "#000000",
                    indexLabelPlacement: "inside",
                    indexLabelFontSize: 20,
                    yValueFormatString: "#.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
            }]
            });
            chart.render();

        }
    </script>
 }

CactusProject/Views/Graph/GraphOrder3.cshtml
@using CactusProject.Utility
@{
    var dateY = DateTime.Now.ToString("yyyy");
}

<div class="text-center">

    <span class="dropdown-header">More Graph</span>

    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder" asp-route-status="@SD.StatusApproved">Graph Pie</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder1" asp-route-status="@SD.StatusApproved">Graph Column</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder2" asp-route-status="@SD.StatusApproved">Graph Bar</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder3" asp-route-status="@SD.StatusApproved">Graph Pyramid</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder4" asp-route-status="@SD.StatusApproved">Graph SplineArea</a>

</div>

<div class="container text-dark mt-4">
    <form asp-action="GraphOrder3">
      <label for="date">Date:</label>
      <input type="date" name="date">
      <input type="submit">
    </form>
    <div class="bg-white"><h4>ยอดขายรวมทั้งหมด @dateY : @ViewBag.sumtotal</h4></div>

    <div id="chartContainer" style="height: 675px; width: 100%;"></div>
</div>

@section Scripts{
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                theme: "light2",
                title: {
                    text: "ยอดขาย @dateY"
                },
                subtitles: [{
                  text: "2565 ถึง @dateY"
                }],
                legend: {
                    horizontalAlign: "right",
                    verticalAlign: "center"
                },
                data: [{
                    type: "pyramid",
                    toolTipContent: "{label} Pm - {z} Bath - {y}%",
                    startAngle: -45,
                    indexLabel: "{y}%",
                    indexLabelFontColor: "#000000",
                    indexLabelPlacement: "inside",
                    indexLabelFontSize: 20,
                    yValueFormatString: "#.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                    }]
            });
            calculatePercentage();
            chart.render();

            function calculatePercentage() {
                var dataPoint = chart.options.data[0].dataPoints;
                var total = dataPoint[0].y;
                for (var i = 0; i < dataPoint.length; i++) {
                    if (i == 0) {
                        chart.options.data[0].dataPoints[i].percentage = 100;
                    } else {
                        chart.options.data[0].dataPoints[i].percentage = ((dataPoint[i].y / total) * 100).toFixed(2);
                    }
                }
            }

        }
    </script>
 }

CactusProject/Views/Graph/GraphOrder4.cshtml
@using CactusProject.Utility
@{
    var dateY = DateTime.Now.ToString("yyyy");
}

<div class="text-center">

    <span class="dropdown-header">More Graph</span>

    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder" asp-route-status="@SD.StatusApproved">Graph Pie</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder1" asp-route-status="@SD.StatusApproved">Graph Column</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder2" asp-route-status="@SD.StatusApproved">Graph Bar</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder3" asp-route-status="@SD.StatusApproved">Graph Pyramid</a>
    <a class="dropdown-item  text-dark" asp-controller="Graph" asp-action="GraphOrder4" asp-route-status="@SD.StatusApproved">Graph SplineArea</a>

</div>

<div class="container text-dark mt-4">
    <form asp-action="GraphOrder4">
      <label for="date">Date:</label>
      <input type="date" name="date">
      <input type="submit">
    </form>
    <div class="bg-white"><h4>ยอดขายรวมทั้งหมด @dateY : @ViewBag.sumtotal</h4></div>

    <div id="chartContainer" style="height: 675px; width: 100%;"></div>
</div>

@section Scripts{
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                title: {
                    text: "ยอดขาย @dateY"
                },
                subtitles: [{
                    text: "2565 ถึง @dateY"
                }],
                axisX: {
                    valueFormatString: "YYYY"
                },
                data: [{
                    type: "splineArea",
                    color: "#FFCC00",
                    toolTipContent: "{label} Pm - {z} Bath - {y}%",
                    startAngle: -45,
                    indexLabel: "{y}%",
                    indexLabelFontColor: "#000000",
                    indexLabelPlacement: "inside",
                    indexLabelFontSize: 20,
                    yValueFormatString: "#.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                    }]
            });
            chart.render();

        }
    </script>
 }