CactusProject/Models/Cactus.cs
using CactusProject.ViewModels;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CactusProject.Models
{
    public class Cactus
    {
        
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public double Price { get; set; }

 
        public double Amount { get; set; }

        [ValidateNever]
        public string ImageUrl { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;

        [Required]
        [Display(Name = "Category Name")]
        public int CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        [ValidateNever]
        public Category Category { get; set; }

        [Required]
        [Display(Name = "Source Name")]
        public int SourceId { get; set; }

        [ForeignKey("SourceId")]
        [ValidateNever]
        public Source Source { get; set; }

        [Required]
        [Display(Name = "Genus Name")]
        public int GenusId { get; set; }

        [ForeignKey("GenusId")]
        [ValidateNever]
        public Genus Genus { get; set; }

        [Required]
        [Display(Name = "Size Name")]
        public int SizeId { get; set; }

        [ForeignKey("SizeId")]
        [ValidateNever]
        public Size Size { get; set; }

        public Cactus()
        {
            Image = new HashSet<Image>();
            Review = new HashSet<Review>();
        }

        [ValidateNever]
        public virtual ICollection<Image> Image { get; set; }

        [ValidateNever]
        public virtual ICollection<Review> Review { get; set; }

    }
}

CactusProject/Controllers/CactusController.cs
using CactusProject.Data;
using CactusProject.Services.Cactuss.IService;
using CactusProject.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CactusProject.Controllers
{
    public class CactusController : Controller
    {
        private readonly CactusContext cactusContext;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly ICactusService cactusService;

        public CactusController(CactusContext cactusContext, IWebHostEnvironment webHostEnvironment,ICactusService cactusService)
        {
            this.cactusContext = cactusContext;
            this.webHostEnvironment = webHostEnvironment;
            this.cactusService = cactusService;
        }
        public IActionResult Index()
        {
            return View(cactusService.GetCactus());
        }

        public IActionResult UpSert(int? id)
        {
            return View(cactusService.GetUpsert(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpSert(CactusVM data, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    //สุ่มชื่อสุ่มไฟล์
                    string fileName = Guid.NewGuid().ToString();
                    //เช็คนามสกุลไฟล์ชื่อ
                    var extension = Path.GetExtension(file.FileName);
                    //เก็บรูปไว้ในไหน
                    var uploads = Path.Combine(wwwRootPath, @"images\products");


                    if (!Directory.Exists(uploads)) Directory.CreateDirectory(uploads);

                    //กรณีมีรูปภาพเดิมต้องลบทิ้งก่อน
                    if (data.Cactus.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, data.Cactus.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    //บันทึกรุปภาพใหม่
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    data.Cactus.ImageUrl = @"\images\products\" + fileName + extension;
                }
            }
            if (data.Cactus.Id != 0)
            {
                cactusContext.ManyCactus.Update(data.Cactus);
                TempData["Success"] = "อัพเดทเสร็จสิน";
            }
            else
            {
                cactusContext.ManyCactus.Add(data.Cactus);
                TempData["Success"] = "สร้างเสร็จสิน";
            }

            cactusContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            cactusService.RemoveCactus(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

CactusProject/Views/Cactus/Index.cshtml
@model IEnumerable<CactusProject.Models.Cactus>

<div style="background-color: #FFFFFF">
    <div class="row btn-light disabled p-2">
        <div class="col-6"><h4>Cactus list</h4></div>
        <div class="col-6 text-end">
            <a class="btn btn-info text-white " asp-controller="Cactus" asp-action="UpSert">Create Cactus</a>
        </div>
    </div>
    <table class="table table-hover pt-2" id="example1" >
        <thead class="table-primary">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th>
                    วัน/เดือน/ปี
                </th>
                <th>
                    ประเภท
                </th>
                
                <th>
                    สายพันธุ์
                </th>
                <th>
                    ขนาด
                </th>
                <th>
                    แหล่งที่มา
                </th>
                
                <th>Update | Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                   @* <td>
                        @Html.Raw(item.Description)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>

                    
                    <td>
                        @Html.DisplayFor(modelItem => item.Genus.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Size.Sizename)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Source.Name)
                    </td>
                    <td>
                        <a class="btn btn-warning mr-2" asp-action="UpSert" asp-route-id="@item.Id">
                           <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a class="btn btn-danger mx-1" asp-action="Delete" asp-route-id="@item.Id"
                        onclick="return confirm('Confirm delete')">
                           <i class="bi bi-x"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CactusProject/Views/Cactus/Upsert.cshtml
@model CactusProject.ViewModels.CactusVM

<h4>@(Model.Cactus.Id != 0 ?"Update":"Create") Cactus</h4>

<hr />
<div class="row border rounded">
    <form asp-action="UpSert" enctype="multipart/form-data" method="post" style="background-color: #FFFFFF">

        <input asp-for="Cactus.Id" hidden/>
        <input asp-for="Cactus.ImageUrl" hidden/>

        <div class="row">
            <div class="col-8">
                <div class="row">Cactus
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Cactus.Name" class="control-label"></label>
                        <input asp-for="Cactus.Name" class="form-control" />
                        <span asp-validation-for="Cactus.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Cactus.Description" class="control-label"></label>
                        <textarea asp-for="Cactus.Description" class="form-control" id="mytextarea"></textarea>
                        <span asp-validation-for="Cactus.Description" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="Cactus.Price" class="control-label"></label>
                        <input asp-for="Cactus.Price" class="form-control" min="1" max="999999" step="1"/>
                        <span asp-validation-for="Cactus.Price" class="text-danger"></span>
                    </div>
                    <div class="form-group col-6">
                        <label asp-for="Cactus.Amount" class="control-label"></label>
                        <input asp-for="Cactus.Amount" class="form-control" min="0" max="999"/>
                        <span asp-validation-for="Cactus.Amount" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Cactus.ImageUrl" class="control-label"></label>
                       <input name="file" type="file" accept="image/*" class="form-control" onchange="ShowImage(event)" id="UploadBox">
                    </div>

                    <div class="form-group col-6">
                        <label asp-for="Cactus.CategoryId" class="control-label"></label>
                        <select asp-for="Cactus.CategoryId" asp-items="@Model.CategoryList" class="form-control">
                            <option disabled selected>-เลือก ประเภท-</option>
                        </select>
                        <span asp-validation-for="Cactus.CategoryId" class="text-danger"></span>

                    </div>
                    <div class="form-group col-6">
                        <label asp-for="Cactus.SourceId" class="control-label"></label>
                        <select asp-for="Cactus.SourceId" asp-items="@Model.SourceList" class="form-control">
                            <option disabled selected>-เลือก แหล่งที่มา-</option>
                        </select>
                        <span asp-validation-for="Cactus.SourceId" class="text-danger"></span>
                        </div>
                        <div class="form-group col-6">
                            <label asp-for="Cactus.GenusId" class="control-label"></label>
                            <select asp-for="Cactus.GenusId" asp-items="@Model.GenusList" class="form-control">
                                <option disabled selected>-เลือก สายพันธุ์-</option>
                            </select>
                            <span asp-validation-for="Cactus.GenusId" class="text-danger"></span>
                        </div>
                        <div class="form-group col-6">
                            <label asp-for="Cactus.SizeId" class="control-label"></label>
                            <select asp-for="Cactus.SizeId" asp-items="@Model.SizeList" class="form-control">
                                <option disabled selected>-เลือก ขนาด-</option>
                            </select>
                            <span asp-validation-for="Cactus.SizeId" class="text-danger"></span>
                        </div>
                        
                    <div class="form-group py-2">
                        @if (Model.Cactus.Id != 0)
                        {
                            <button type="submit" class="btn btn-success">Update</button>
                        }
                        else
                        {
                            <button type="submit" onclick="return ValidateImage()" class="btn btn-success">Create</button>
                        }
                        <a class="btn btn-outline-secondary" asp-action="Index">Back to list</a>
                    </div>
                </div>
            </div>
            @{
                string ImgUrl = "http://10.103.0.30/Cs64/s09/CAC" + @Model.Cactus.ImageUrl;
            }
            <div class="col-4">
                <img src=@ImgUrl width="100%" class="m-2 border rounded" id="output" />
            </div>
        </div>

    </form>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

<script>
    function ShowImage(event){
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    }

    tinymce.init({
    selector: '#mytextarea',
    plugins: [
      'a11ychecker','advlist','advcode','advtable','autolink','checklist','export',
      'lists','link','image','charmap','preview','anchor','searchreplace','visualblocks',
      'powerpaste','fullscreen','formatpainter','insertdatetime','media','table','help','wordcount'
    ],
    toolbar: 'undo redo | formatpainter casechange blocks | bold italic backcolor | ' +
      'alignleft aligncenter alignright alignjustify | ' +
      'bullist numlist checklist outdent indent | removeformat | a11ycheck code table help'
    });

    function ValidateImage(){
         if(document.getElementById("UploadBox").value ==""){
             Swal.fire('No Image')
             return false
         }

         return true
     }
</script>
}